#
# Retrieve vlan information, parse, store as facts
#

---
- hosts: switches
  vars:
    target: 22
  tasks:
  - set_fact:
      trunk_status:
        interfaces:
          Gi0/0:
            trunk_vlans: 1,10,20,21,23,24,205
          Gi0/1:
            trunk_vlans: 1,10,20,21-23,24,25,26
          Gi0/2:
            trunk_vlans: 1,10,20,20,22,700,702
          Gi0/3:
            trunk_vlans: 1,10,20,22-23,24
  - name: Generate graph file
    template: src={{template|default('vlan-graph.j2')}} dest=./{{output|default('test-output.dot')}}
    run_once: true
